// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfQwUi4gOZFdWL5HrvyHYzAhETo5NdwRI',
    appId: '1:663147332063:web:1fe6e8246b6679dd19c46a',
    messagingSenderId: '663147332063',
    projectId: 'gokul-portfolio-dbdda',
    authDomain: 'gokul-portfolio-dbdda.firebaseapp.com',
    storageBucket: 'gokul-portfolio-dbdda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJoGJ6Lzk9BKeG83aM6FIf9r3dldhCtMI',
    appId: '1:663147332063:android:ae9f6984cf3c574d19c46a',
    messagingSenderId: '663147332063',
    projectId: 'gokul-portfolio-dbdda',
    storageBucket: 'gokul-portfolio-dbdda.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgtYV_0aW1Itv0_zycwskr531fLvA1tTc',
    appId: '1:663147332063:ios:fc111018fb6af7ac19c46a',
    messagingSenderId: '663147332063',
    projectId: 'gokul-portfolio-dbdda',
    storageBucket: 'gokul-portfolio-dbdda.firebasestorage.app',
    iosBundleId: 'com.example.gokulPortfolio',
  );
}
